const test=require('node:test');const assert=require('node:assert/strict');
const modulePromise=import('../../src/operations/production-route-disable.mjs');
const base={zone:'safe-link.co.kr',hostname:'inventory.safe-link.co.kr',tunnelName:'sqcm-i-inventory-production',preserveExistingTunnels:true,preserveLoopbackServices:true,productionTunnelId:'994b5a27-cba4-4958-aecf-ed43db8730ef',tokenReferencePresent:true,execute:false,insideWindow:false,confirmed:false};
test('route disable dry-run은 외부 변경 없이 준비 상태만 판정한다',async()=>{const {evaluateProductionRouteDisableGate}=await modulePromise;const r=evaluateProductionRouteDisableGate(base);assert.equal(r.status,'PASS_ROUTE_DISABLE_DRY_RUN_READY');assert.equal(r.externalMutationPerformed,false);assert.equal(r.actualPostCutoverRollback,'NOT_RUN');});
test('tunnel 또는 token reference가 없으면 입력 대기다',async()=>{const {evaluateProductionRouteDisableGate}=await modulePromise;const r=evaluateProductionRouteDisableGate({...base,productionTunnelId:null,tokenReferencePresent:false});assert.equal(r.status,'READY_WAIT_ROUTE_DISABLE_INPUTS');assert.deepEqual(r.pending,['PRODUCTION_TUNNEL_MISSING','CLOUDFLARE_DNS_TOKEN_REFERENCE_MISSING']);});
test('정확하지 않은 zone hostname tunnel을 차단한다',async()=>{const {evaluateProductionRouteDisableGate}=await modulePromise;const r=evaluateProductionRouteDisableGate({...base,hostname:'wrong.example'});assert.equal(r.status,'FAIL_ROUTE_DISABLE_CONTRACT');assert.ok(r.failures.includes('ROUTE_DISABLE_HOSTNAME_INVALID'));});
test('변경창 밖 execute를 차단한다',async()=>{const {evaluateProductionRouteDisableGate}=await modulePromise;const r=evaluateProductionRouteDisableGate({...base,execute:true,confirmed:true});assert.equal(r.status,'FAIL_ROUTE_DISABLE_OUTSIDE_CHANGE_WINDOW');});
test('변경창 안에서도 exact 확인 전에는 대기한다',async()=>{const {evaluateProductionRouteDisableGate}=await modulePromise;const r=evaluateProductionRouteDisableGate({...base,execute:true,insideWindow:true});assert.equal(r.status,'READY_WAIT_ROUTE_DISABLE_CONFIRMATION');});
test('record 삭제와 authoritative 부재 뒤 public rollback만 PASS한다',async()=>{const {classifyProductionRouteDisableResult}=await modulePromise;const pending=classifyProductionRouteDisableResult({recordDeleted:true,recordCountAfter:0,dnsPublishedAfter:true});assert.equal(pending.status,'READY_WAIT_PUBLIC_DNS_PROPAGATION');const pass=classifyProductionRouteDisableResult({recordDeleted:true,recordCountAfter:0,dnsPublishedAfter:false});assert.equal(pass.actualPostCutoverRollback,'PASS');});
