const test=require('node:test');const assert=require('node:assert/strict');const modulePromise=import('../../src/operations/production-uat-actor-provision.mjs');
const refs={ADMIN:true,MANAGER:true,USER:true};const base={environment:'production',organizationCode:'SEOWON',preserveExistingUsers:true,failOnIdentityConflict:true,approvalReferencePresent:true,credentialReferences:refs,execute:false,insideWindow:false,confirmed:false};
test('완전한 참조 dry-run은 계정 변경 없이 준비 PASS다',async()=>{const {evaluateProductionUatActorProvisionGate}=await modulePromise;const r=evaluateProductionUatActorProvisionGate(base);assert.equal(r.status,'PASS_UAT_ACTOR_PROVISION_DRY_RUN_READY');assert.equal(r.externalMutationPerformed,false);});
test('승인 또는 역할별 credential 참조가 없으면 입력 대기다',async()=>{const {evaluateProductionUatActorProvisionGate}=await modulePromise;const r=evaluateProductionUatActorProvisionGate({...base,approvalReferencePresent:false,credentialReferences:{ADMIN:true,MANAGER:false,USER:false}});assert.deepEqual(r.pending,['PRODUCTION_UAT_ACTOR_APPROVAL_REFERENCE_MISSING','MANAGER_CREDENTIAL_REFERENCE_MISSING','USER_CREDENTIAL_REFERENCE_MISSING']);});
test('Production·SEOWON·보존 계약 변조를 거부한다',async()=>{const {evaluateProductionUatActorProvisionGate}=await modulePromise;assert.equal(evaluateProductionUatActorProvisionGate({...base,environment:'staging'}).status,'FAIL_UAT_ACTOR_PROVISION_CONTRACT');assert.equal(evaluateProductionUatActorProvisionGate({...base,preserveExistingUsers:false}).status,'FAIL_UAT_ACTOR_PROVISION_CONTRACT');});
test('변경창 밖 execute는 fail-closed 한다',async()=>{const {evaluateProductionUatActorProvisionGate}=await modulePromise;assert.equal(evaluateProductionUatActorProvisionGate({...base,execute:true,confirmed:true}).status,'FAIL_UAT_ACTOR_PROVISION_OUTSIDE_CHANGE_WINDOW');});
test('변경창 안에서도 exact 확인을 요구한다',async()=>{const {evaluateProductionUatActorProvisionGate}=await modulePromise;assert.equal(evaluateProductionUatActorProvisionGate({...base,execute:true,insideWindow:true}).status,'READY_WAIT_UAT_ACTOR_PROVISION_CONFIRMATION');assert.equal(evaluateProductionUatActorProvisionGate({...base,execute:true,insideWindow:true,confirmed:true}).status,'READY_UAT_ACTOR_PROVISION_EXECUTION');});
test('승인 파일은 세 역할·고유 이메일·승인 상태를 강제한다',async()=>{const {validateProductionUatActorApproval}=await modulePromise;const valid={schemaVersion:1,environment:'production',organizationCode:'SEOWON',approvalId:'P6UAT-20260911',approvedAt:'2026-09-01T10:00:00Z',actors:[{role:'ADMIN',email:'a@example.com',approved:true},{role:'MANAGER',email:'m@example.com',approved:true},{role:'USER',email:'u@example.com',approved:true}]};assert.equal(validateProductionUatActorApproval(valid),true);assert.equal(validateProductionUatActorApproval({...valid,actors:[...valid.actors.slice(0,2),{role:'MANAGER',email:'u@example.com',approved:true}]}),false);});
test('세 역할 MFA scope audit와 세션 0만 PASS한다',async()=>{const {classifyProductionUatActorProvisionResult}=await modulePromise;const valid={roles:['ADMIN','MANAGER','USER'],activeCount:3,mfaEnabledCount:3,scopeCount:3,auditCount:3,sessionCountAfter:0};assert.equal(classifyProductionUatActorProvisionResult(valid).status,'PASS_PRODUCTION_UAT_ACTORS_PROVISIONED');assert.equal(classifyProductionUatActorProvisionResult({...valid,mfaEnabledCount:2}).status,'FAIL_UAT_ACTOR_PROVISION_RESULT');});
